// website/app/components/Pagination.vue
<template>
  <nav
    class="flex w-full justify-between items-center space-x-4 mt-6"
    role="navigation"
    aria-label="pagination"
  >
    <!-- Previous Button -->
    <button
      :disabled="currentPage === 1"
      @click="prevPage"
      :class="[
        'px-4 py-2 rounded-full border',
        currentPage === 1
          ? 'cursor-not-allowed bg-gray-200 text-gray-500 border-gray-300'
          : 'bg-white text-gray-700 border-gray-400 hover:bg-gray-100',
      ]"
      aria-label="Previous Page"
    >
      Previous
    </button>

    <!-- Page Number Links -->
    <ul class="flex space-x-2">
      <li v-for="page in pages" :key="page">
        <button
          @click="selectPage(page)"
          :aria-current="page === currentPage ? 'page' : undefined"
          :class="[
            'px-3 py-1 rounded-full border',
            page === currentPage
              ? 'bg-black text-white border-white'
              : 'bg-white text-gray-700 border-gray-300 hover:bg-gray-100',
          ]"
        >
          {{ page }}
        </button>
      </li>
    </ul>

    <!-- Next Button -->
    <button
      :disabled="currentPage === totalPages"
      @click="nextPage"
      :class="[
        'px-4 py-2 rounded-full border',
        currentPage === totalPages
          ? 'cursor-not-allowed bg-gray-200 text-gray-500 border-gray-300'
          : 'bg-white text-gray-700 border-gray-400 hover:bg-gray-100',
      ]"
      aria-label="Next Page"
    >
      Next
    </button>
  </nav>
</template>

<script setup lang="ts">
import { computed, defineProps, defineEmits } from "vue";

const props = defineProps<{
  currentPage: number;
  totalPages: number;
}>();

const emit = defineEmits<{
  (event: "pageChanged", page: number): void;
}>();

const pages = computed(() => {
  return Array.from({ length: props.totalPages }, (_, i) => i + 1);
});

function selectPage(page: number) {
  if (page !== props.currentPage) {
    emit("pageChanged", page);
  }
}

function nextPage() {
  if (props.currentPage < props.totalPages) {
    emit("pageChanged", props.currentPage + 1);
  }
}

function prevPage() {
  if (props.currentPage > 1) {
    emit("pageChanged", props.currentPage - 1);
  }
}
</script>

<style scoped></style>

// packages/manager/admin/app/components/pagination.tsx
import { useState, useEffect } from "react";

interface PaginationProps {
  totalItems: number;
  itemsPerPage: number;
  currentPage: number;
  onPageChange: (page: number) => void;
}

export function Pagination({
  totalItems,
  itemsPerPage,
  currentPage,
  onPageChange,
}: PaginationProps) {
  const totalPages = Math.ceil(totalItems / itemsPerPage);
  const [visiblePages, setVisiblePages] = useState<number[]>([]);

  useEffect(() => {
    const maxVisible = 5;
    let startPage = Math.max(1, currentPage - Math.floor(maxVisible / 2));
    let endPage = startPage + maxVisible - 1;

    if (endPage > totalPages) {
      endPage = totalPages;
      startPage = Math.max(1, endPage - maxVisible + 1);
    }

    const pages = [];
    for (let i = startPage; i <= endPage; i++) {
      pages.push(i);
    }
    setVisiblePages(pages);
  }, [currentPage, totalPages]);

  if (totalPages <= 1) return null;

  return (
    <div className="flex items-center justify-between mt-4">
      <div className="text-sm text-muted-foreground">
        Showing {(currentPage - 1) * itemsPerPage + 1}-
        {Math.min(currentPage * itemsPerPage, totalItems)} of {totalItems} tasks
      </div>
      <div className="flex gap-1">
        <button
          onClick={() => onPageChange(currentPage - 1)}
          disabled={currentPage === 1}
          className="px-3 py-1 rounded border disabled:opacity-50 disabled:cursor-not-allowed"
        >
          Previous
        </button>

        {visiblePages[0] > 1 && (
          <>
            <button
              onClick={() => onPageChange(1)}
              className={`px-3 py-1 rounded border ${currentPage === 1 ? "bg-primary text-primary-foreground" : ""}`}
            >
              1
            </button>
            {visiblePages[0] > 2 && <span className="px-3 py-1">...</span>}
          </>
        )}

        {visiblePages.map((page) => (
          <button
            key={page}
            onClick={() => onPageChange(page)}
            className={`px-3 py-1 rounded border ${currentPage === page ? "bg-primary text-primary-foreground" : ""}`}
          >
            {page}
          </button>
        ))}

        {visiblePages[visiblePages.length - 1] < totalPages && (
          <>
            {visiblePages[visiblePages.length - 1] < totalPages - 1 && (
              <span className="px-3 py-1">...</span>
            )}
            <button
              onClick={() => onPageChange(totalPages)}
              className={`px-3 py-1 rounded border ${currentPage === totalPages ? "bg-primary text-primary-foreground" : ""}`}
            >
              {totalPages}
            </button>
          </>
        )}

        <button
          onClick={() => onPageChange(currentPage + 1)}
          disabled={currentPage === totalPages}
          className="px-3 py-1 rounded border disabled:opacity-50 disabled:cursor-not-allowed"
        >
          Next
        </button>
      </div>
    </div>
  );
}
